import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "@/styles/Home.module.css";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <Image alt="logo" />
          <Link href="" passHref>
            Home
          </Link>
          <Link href="/events" passHref>
            Events
          </Link>
          <Link href="/about-us" passHref>
            About Us
          </Link>
        </nav>
      </header>
      <main className={styles.main}>
        {data.map((ev) => (
          <Link key={ev.id} href={`/events/${ev.id}`} passHref>
            <Image width={300} height={300} alt={ev.title} src={ev.image} />
            <h2>{ev.title}</h2>
            <p>{ev.description}</p>
          </Link>
        ))}
      </main>
      <footer className={styles.footer}>
        <p> © 2023 Events Page</p>
      </footer>
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("/data/data.json");

  // // For fetching from an external API
  // const res = await fetch("URL");
  // const data = await res.json();
  // code inside here won't be shown to the client side (before the return)
  return {
    props: {
      data: events_categories,
    },
  };
}
