import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import { HomePage } from "../src/components/home/home-page.js";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage data={data} />
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("/data/data.json");

  // // For fetching from an external API
  // const res = await fetch("URL");
  // const data = await res.json();
  // code inside here won't be shown to the client side (before the return)
  return {
    props: {
      data: events_categories,
    },
  };
}
